"""Scan API routes.

Endpoints
---------
POST  /api/scans/run                       — validate, lock repo, create scan record,
                                             enqueue Arq job, return {scan_id, repository_id, status}.
GET   /api/scans/{scan_id}                 — full scan detail with agent findings.
GET   /api/scans/{scan_id}/status          — return live progress and status from DB.
POST  /api/scans/{scan_id}/cancel          — request scan cancellation via Redis flag.
GET   /api/scans/{scan_id}/patch           — unified diff generated by the auto-fix pipeline.
POST  /api/scans/{scan_id}/create-pr       — create GitHub PR from the stored patch.
GET   /api/scans/{scan_id}/patch-annotations — inline annotations keyed to the diff.

Per-repository lock
-------------------
Before enqueueing, the handler acquires a distributed Redis lock keyed by
``repository_id``.  If the lock is already held (another scan in progress),
a 409 is returned immediately.  The lock is released by the Arq worker after
the scan finishes (success, failure, or cancellation).

Cancellation protocol
---------------------
The cancel endpoint sets a Redis flag ``scan:cancel:{scan_id}``.
The scan orchestrator polls this flag between pipeline stages and raises
``ScanCancelledError`` on detection, transitioning the scan to "cancelled".

Design rules
------------
- Zero business logic in handlers.
- Domain errors (ValidationError, NotFoundError, ScanAlreadyRunningError)
  are AppError subclasses → caught by the global handler in main.py.
- Unexpected exceptions propagate to FastAPI's default 500 handler.
"""
from __future__ import annotations

import io
import json
import os
import shutil
import uuid
import zipfile
from pathlib import Path
from typing import Optional

import pathspec
from fastapi import APIRouter, Depends, File, Form, Query, Request, UploadFile, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.mappers import scan_to_full, scan_to_summary
from app.api.schemas import (
    AgentFindingSummary,
    AnnotationResponse,
    ErrorResponse,
    PatchResponse,
    PRResponse,
    ScanCancelResponse,
    ScanConfig,
    ScanFullSchema,
    ScanListEnvelope,
    ScanRunRequest,
    ScanRunResponse,
    ScanStatusResponse,
    ScanSummarySchema,
)
from app.core.exceptions import AppError, NotFoundError, ScanAlreadyRunningError, ValidationError
from app.core.logging import get_logger
from app.domain.enums import ScanStatus
from app.infrastructure.background_tasks import enqueue_scan
from app.infrastructure.db.models import ScanModel
from app.infrastructure.db.scan_repository import ScanRepository
from app.infrastructure.db.session import get_db_session
from app.infrastructure.local_repo_validator import LocalRepoValidator
from app.infrastructure.redis_client import RedisClient

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Upload constants
# ---------------------------------------------------------------------------

_SCAN_TMP_DIR = Path("/tmp/scans")
_UPLOAD_MAX_TOTAL_BYTES = 500 * 1_048_576   # 500 MB
_UPLOAD_MAX_FILE_BYTES  = 10  * 1_048_576   # 10 MB per individual file (larger silently skipped)

_SKIP_DIR_NAMES: frozenset[str] = frozenset({
    "node_modules", ".git", "__pycache__", ".next", "dist", "build",
    ".mypy_cache", ".pytest_cache", "coverage", ".tox", "venv", ".venv",
    "env", "vendor", "bower_components", ".turbo", ".nuxt", ".output",
})

_SOURCE_EXTENSIONS: frozenset[str] = frozenset({
    ".py", ".js", ".ts", ".jsx", ".tsx",
    ".java", ".kt", ".scala", ".go", ".rb", ".php",
    ".cs", ".cpp", ".cc", ".cxx", ".c", ".h", ".hpp",
    ".rs", ".swift", ".dart", ".r", ".sh", ".bash",
})

router = APIRouter(
    prefix="/api/scans",
    tags=["Scans"],
)

# ---------------------------------------------------------------------------
# Dependency helpers
# ---------------------------------------------------------------------------


async def get_scan_repository(
    session: AsyncSession = Depends(get_db_session),
) -> ScanRepository:
    return ScanRepository(session)


def get_redis_client(request: Request) -> RedisClient:
    """Return a RedisClient backed by the app-level Arq pool."""
    return RedisClient(request.app.state.arq_pool)


# ---------------------------------------------------------------------------
# POST /api/scans/run
# ---------------------------------------------------------------------------


@router.post(
    "/run",
    response_model=ScanRunResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Trigger a new scan",
    description=(
        "Validates the source, acquires a per-repository distributed lock, "
        "creates a scan record (status='queued'), enqueues the scan on the "
        "Arq task queue, and immediately returns the scan and repository IDs. "
        "Returns 409 if a scan is already running for the same repository."
    ),
    operation_id="run_scan",
    responses={
        202: {
            "description": "Scan queued; scan_id and repository_id returned.",
            "content": {
                "application/json": {
                    "example": {
                        "scan_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                        "repository_id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
                        "status": "queued",
                    }
                }
            },
        },
        400: {"model": ErrorResponse, "description": "Invalid source input."},
        409: {"model": ErrorResponse, "description": "Scan already running for this repository."},
        422: {"model": ErrorResponse, "description": "Pydantic validation error."},
        500: {"model": ErrorResponse, "description": "Unexpected server error."},
    },
)
async def run_scan(
    http_request: Request,
    request: ScanRunRequest,
    scan_repo: ScanRepository = Depends(get_scan_repository),
    redis: RedisClient = Depends(get_redis_client),
) -> ScanRunResponse:
    """Queue a new scan and return immediately.

    The heavy lifting (cloning, agent execution, scoring) runs in the Arq
    worker process.  Poll ``GET /api/scans/{scan_id}/status`` for progress.
    """
    logger.info(
        "api.run_scan.start",
        source_type=request.source_type,
        repository_url=request.repository_url,
        local_path=request.local_path,
        branch=request.branch,
        scan_mode=(request.config.mode if request.config else "deep"),
    )

    source_reference, repo_name = _resolve_source_reference(request)

    # Pre-flight local path validation — returns a 400 immediately so the
    # client doesn't have to wait for the background worker to report failure.
    if request.source_type == "local":
        validator = LocalRepoValidator()
        source_reference = await validator.validate(source_reference)
        repo_name = Path(source_reference).name

    # Find or create the repository record.
    repository = await scan_repo.find_or_create_repository(
        name=repo_name,
        repo_url=request.repository_url,
        source_type=request.source_type,
    )

    # Acquire the per-repository distributed lock (TTL = scan_lock_ttl_seconds).
    # We need a temporary scan_id to store in the lock value so the worker
    # can verify ownership when releasing.
    import uuid as _uuid
    from app.core.config import settings

    tentative_scan_id = _uuid.uuid4()
    acquired = await redis.acquire_repo_lock(
        repository_id=repository.id,
        scan_id=tentative_scan_id,
        ttl_seconds=settings.scan_lock_ttl_seconds,
    )
    if not acquired:
        raise ScanAlreadyRunningError(str(repository.id))

    # Create the scan record with status="queued", using the same UUID.
    config_dict = request.config.model_dump() if request.config else None
    scan_mode = (request.config.mode if request.config else None) or "deep"
    scan = await scan_repo.create_scan(
        repository_id=repository.id,
        source_type=request.source_type,
        source_reference=source_reference,
        scan_id=tentative_scan_id,
        branch=request.branch,
        scan_mode=scan_mode,
        scan_config_json=config_dict,
    )

    # Enqueue on the Arq task queue.
    job_id = await enqueue_scan(
        pool=http_request.app.state.arq_pool,
        scan_id=scan.id,
        repository_id=repository.id,
    )

    logger.info(
        "api.run_scan.queued",
        scan_id=str(scan.id),
        repository_id=str(repository.id),
        job_id=job_id,
    )
    return ScanRunResponse(
        scan_id=scan.id,
        repository_id=repository.id,
        status=ScanStatus.QUEUED.value,
    )


# ---------------------------------------------------------------------------
# Helpers for /upload
# ---------------------------------------------------------------------------


def _is_skipped_path(rel_path: str) -> bool:
    """Return True if the relative file path should be excluded from uploads."""
    parts = rel_path.replace("\\", "/").split("/")
    return any(part in _SKIP_DIR_NAMES for part in parts)


def _safe_write(base: Path, rel_path: str, data: bytes) -> None:
    """Write *data* to *base/rel_path*, blocking any traversal attempt."""
    rel_path = rel_path.replace("\\", "/").lstrip("/")
    for segment in rel_path.split("/"):
        if segment in ("", ".", ".."):
            raise ValidationError(f"Unsafe path in upload: {rel_path!r}")
    dest = (base / rel_path).resolve()
    if not str(dest).startswith(str(base.resolve())):
        raise ValidationError(f"Path traversal detected: {rel_path!r}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)


def _assert_has_source_files(directory: Path) -> None:
    """Raise ValidationError if the directory has no recognised source files."""
    for _, _, filenames in os.walk(str(directory)):
        for fname in filenames:
            if Path(fname).suffix.lower() in _SOURCE_EXTENSIONS:
                return
    raise ValidationError(
        "No recognised source files found in the uploaded folder. "
        "Expected files such as .py, .js, .ts, .java, .go, .rb, .php, .cs, .cpp, .rs."
    )


def _apply_gitignore_filters(directory: Path) -> int:
    """Parse every .gitignore found under *directory* and delete matching files.

    Each ``.gitignore`` applies to files in the directory that contains it and
    all of its subdirectories (same semantics as Git).  The function walks the
    tree in top-down order so parent ignore rules are processed before children.

    Returns the number of files deleted.
    """
    deleted = 0
    # Collect (gitignore_dir, pathspec) pairs, shallowest first.
    matchers: list[tuple[Path, pathspec.PathSpec]] = []

    for root, dirs, files in os.walk(str(directory), topdown=True):
        # Skip already-excluded dirs so we don't look inside them.
        dirs[:] = [d for d in dirs if d not in _SKIP_DIR_NAMES]

        if ".gitignore" not in files:
            continue
        gi_path = Path(root) / ".gitignore"
        try:
            lines = gi_path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        spec = pathspec.PathSpec.from_lines("gitwildmatch", lines)
        matchers.append((Path(root), spec))

    if not matchers:
        return 0

    # Second pass: delete files that match any applicable gitignore spec.
    for root, _, files in os.walk(str(directory), topdown=True):
        for fname in files:
            if fname == ".gitignore":
                continue  # keep the gitignore file itself
            file_path = Path(root) / fname
            for gi_dir, spec in matchers:
                # Only apply this spec to files inside its directory.
                try:
                    rel = file_path.relative_to(gi_dir)
                except ValueError:
                    continue  # file is not under this gitignore's directory
                if spec.match_file(str(rel).replace("\\", "/")):
                    try:
                        file_path.unlink()
                        deleted += 1
                    except OSError:
                        pass
                    break  # no need to check further matchers for this file

    # Remove directories that are now empty (best-effort).
    for root, dirs, files in os.walk(str(directory), topdown=False):
        if root == str(directory):
            continue
        try:
            if not any(Path(root).iterdir()):
                Path(root).rmdir()
        except OSError:
            pass

    return deleted


# ---------------------------------------------------------------------------
# POST /api/scans/upload
# ---------------------------------------------------------------------------


@router.post(
    "/upload",
    response_model=ScanRunResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Upload a local repository folder and scan it",
    description=(
        "Accept a folder upload (browser webkitdirectory picker) or a single "
        ".zip archive, extract to a shared temp volume, and queue a scan.\n\n"
        "Works from **any OS** — Windows, Mac, Linux — whether the backend runs "
        "locally, in Docker, or in Azure. No volume mounts or path configuration required."
    ),
    operation_id="upload_scan",
    responses={
        202: {"description": "Scan queued; scan_id and repository_id returned."},
        400: {"model": ErrorResponse, "description": "Invalid upload or no source files found."},
        409: {"model": ErrorResponse, "description": "Scan already running for this repository."},
        413: {"model": ErrorResponse, "description": "Upload exceeds size limit."},
        422: {"model": ErrorResponse, "description": "Validation error."},
    },
)
async def upload_scan(
    http_request: Request,
    files: list[UploadFile] = File(
        ...,
        description=(
            "Project files from a folder picker (webkitdirectory) or a single .zip archive. "
            "node_modules, .git, and build artifacts should be excluded by the client."
        ),
    ),
    repo_name: str = Form(..., description="Human-readable name for this project."),
    config: Optional[str] = Form(default=None, description="JSON-serialised ScanConfig."),
    scan_repo: ScanRepository = Depends(get_scan_repository),
    redis: RedisClient = Depends(get_redis_client),
) -> ScanRunResponse:
    """Queue a scan from an uploaded folder or ZIP archive.

    Files are written to the shared ``/tmp/scans/{scan_id}/`` volume that is
    mounted in both the API container and every Arq worker container.
    """
    import uuid as _uuid
    from app.core.config import settings

    scan_id = _uuid.uuid4()
    upload_dir = _SCAN_TMP_DIR / str(scan_id)
    upload_dir.mkdir(parents=True, exist_ok=True)

    try:
        total_bytes = 0

        is_zip = (
            len(files) == 1
            and (files[0].filename or "").lower().endswith(".zip")
        )

        if is_zip:
            # ── ZIP upload ────────────────────────────────────────────────
            raw = await files[0].read()
            if len(raw) > _UPLOAD_MAX_TOTAL_BYTES:
                raise AppError(
                    f"Upload exceeds the {_UPLOAD_MAX_TOTAL_BYTES // 1_048_576} MB limit.",
                    status_code=413,
                )
            try:
                with zipfile.ZipFile(io.BytesIO(raw)) as zf:
                    for info in zf.infolist():
                        if info.is_dir():
                            continue
                        rel = info.filename.replace("\\", "/")
                        if _is_skipped_path(rel):
                            continue
                        if info.file_size > _UPLOAD_MAX_FILE_BYTES:
                            continue
                        data = zf.read(info.filename)
                        _safe_write(upload_dir, rel, data)
            except zipfile.BadZipFile as exc:
                raise ValidationError("Uploaded file is not a valid ZIP archive.") from exc

        else:
            # ── Multi-file folder upload ───────────────────────────────────
            for uf in files:
                rel_path = uf.filename or "unknown"
                if _is_skipped_path(rel_path):
                    await uf.read()  # drain to avoid resource leak
                    continue
                data = await uf.read()
                if len(data) > _UPLOAD_MAX_FILE_BYTES:
                    continue  # silently skip oversized individual files
                total_bytes += len(data)
                if total_bytes > _UPLOAD_MAX_TOTAL_BYTES:
                    raise AppError(
                        f"Upload exceeds the {_UPLOAD_MAX_TOTAL_BYTES // 1_048_576} MB limit.",
                        status_code=413,
                    )
                _safe_write(upload_dir, rel_path, data)

        # ── Apply .gitignore rules (safety net — also covers ZIP uploads) ─
        _removed = _apply_gitignore_filters(upload_dir)
        if _removed:
            logger.info("upload.gitignore_filtered", files_removed=_removed)

        _assert_has_source_files(upload_dir)

        # ── Parse optional ScanConfig ────────────────────────────────────
        config_dict: dict | None = None
        scan_mode = "deep"
        if config:
            try:
                config_dict = json.loads(config)
                scan_mode = config_dict.get("mode", "deep")
            except json.JSONDecodeError:
                pass

        # ── Find-or-create repository record ────────────────────────────
        repository = await scan_repo.find_or_create_repository(
            name=repo_name.strip() or "uploaded-repo",
            repo_url=None,
            source_type="local",
        )

        # ── Per-repo distributed lock ────────────────────────────────────
        acquired = await redis.acquire_repo_lock(
            repository_id=repository.id,
            scan_id=scan_id,
            ttl_seconds=settings.scan_lock_ttl_seconds,
        )
        if not acquired:
            raise ScanAlreadyRunningError(str(repository.id))

        # ── Create scan record ────────────────────────────────────────────
        scan = await scan_repo.create_scan(
            repository_id=repository.id,
            source_type="local",
            source_reference=str(upload_dir),
            scan_id=scan_id,
            scan_mode=scan_mode,
            scan_config_json=config_dict,
        )

        # ── Enqueue on Arq ────────────────────────────────────────────────
        job_id = await enqueue_scan(
            pool=http_request.app.state.arq_pool,
            scan_id=scan.id,
            repository_id=repository.id,
        )

        logger.info(
            "api.upload_scan.queued",
            scan_id=str(scan.id),
            repo_name=repo_name,
            file_count=len(files),
            total_bytes=total_bytes,
            job_id=job_id,
        )
        return ScanRunResponse(
            scan_id=scan.id,
            repository_id=repository.id,
            status=ScanStatus.QUEUED.value,
        )

    except (AppError, ValidationError):
        shutil.rmtree(upload_dir, ignore_errors=True)
        raise
    except Exception:
        shutil.rmtree(upload_dir, ignore_errors=True)
        raise


@router.get(
    "/{scan_id}/status",
    response_model=ScanStatusResponse,
    summary="Get scan status and progress",
    description=(
        "Returns the current status and progress percentage for the given scan. "
        "Poll this endpoint to track live execution progress."
    ),
    operation_id="get_scan_status",
    responses={
        200: {
            "description": "Scan status returned.",
            "content": {
                "application/json": {
                    "examples": {
                        "running": {
                            "summary": "Scan in progress",
                            "value": {
                                "scan_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                                "status": "running",
                                "progress_percentage": 45,
                                "error_message": None,
                            },
                        },
                        "completed": {
                            "summary": "Scan completed",
                            "value": {
                                "scan_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                                "status": "completed",
                                "progress_percentage": 100,
                                "error_message": None,
                            },
                        },
                        "failed": {
                            "summary": "Scan failed",
                            "value": {
                                "scan_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                                "status": "failed",
                                "progress_percentage": 35,
                                "error_message": "Repository clone timed out after 30s.",
                            },
                        },
                    }
                }
            },
        },
        404: {"model": ErrorResponse, "description": "Scan not found."},
    },
)
async def get_scan_status(
    scan_id: uuid.UUID,
    scan_repo: ScanRepository = Depends(get_scan_repository),
) -> ScanStatusResponse:
    """Return the current status and progress for a scan."""
    logger.info("api.get_scan_status", scan_id=str(scan_id))
    scan = await scan_repo.get_scan(scan_id)
    return ScanStatusResponse(
        scan_id=scan.id,
        status=scan.status,
        progress_percentage=scan.progress_percentage,
        error_message=scan.error_message,
    )


# ---------------------------------------------------------------------------
# POST /api/scans/{scan_id}/cancel
# ---------------------------------------------------------------------------


@router.post(
    "/{scan_id}/cancel",
    response_model=ScanCancelResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Request scan cancellation",
    description=(
        "Sets a cancellation flag in Redis.  The scan orchestrator checks this "
        "flag between pipeline stages and transitions the scan to 'cancelled'. "
        "Returns 202 immediately — the scan may still be running for a short "
        "time while the current stage completes."
    ),
    operation_id="cancel_scan",
    responses={
        202: {"description": "Cancellation requested."},
        404: {"model": ErrorResponse, "description": "Scan not found."},
        409: {"model": ErrorResponse, "description": "Scan is already completed or failed."},
    },
)
async def cancel_scan(
    scan_id: uuid.UUID,
    scan_repo: ScanRepository = Depends(get_scan_repository),
    redis: RedisClient = Depends(get_redis_client),
) -> ScanCancelResponse:
    """Request cancellation for a queued or running scan."""
    logger.info("api.cancel_scan", scan_id=str(scan_id))

    scan = await scan_repo.get_scan(scan_id)
    terminal = {ScanStatus.COMPLETED.value, ScanStatus.FAILED.value, ScanStatus.CANCELLED.value}
    if scan.status in terminal:
        from app.core.exceptions import AppError
        raise AppError(
            f"Scan '{scan_id}' is already in terminal state '{scan.status}'.",
            status_code=409,
        )

    await redis.request_cancellation(scan_id)
    logger.info("api.cancel_scan.flag_set", scan_id=str(scan_id))

    return ScanCancelResponse(scan_id=scan_id, status="cancellation_requested")


# ---------------------------------------------------------------------------
# GET /api/scans  — list scans
# ---------------------------------------------------------------------------


@router.get(
    "",
    response_model=ScanListEnvelope,
    summary="List scans",
    description=(
        "Returns a paginated list of scans, optionally filtered by repository and "
        "status.  Results are ordered newest-first."
    ),
    operation_id="list_scans",
    responses={
        200: {"description": "Paginated scan list."},
    },
)
async def list_scans(
    repository_id: uuid.UUID | None = Query(default=None, description="Filter by repository."),
    status_filter: str | None = Query(default=None, alias="status", description="Filter by status."),
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
    scan_repo: ScanRepository = Depends(get_scan_repository),
) -> ScanListEnvelope:
    scans = await scan_repo.list_scans(
        repository_id=repository_id,
        status=status_filter,
        limit=limit,
        offset=offset,
        load_agents=False,
        load_repo=True,
    )
    total = await scan_repo.count_scans(repository_id=repository_id, status=status_filter)

    items = [_scan_to_summary(s) for s in scans]
    return ScanListEnvelope(items=items, total=total)





@router.get(
    "/{scan_id}",
    response_model=ScanFullSchema,
    summary="Get full scan detail",
    description=(
        "Returns the full scan result including per-agent findings, overall score, "
        "risk level, scan mode, branch, and patch availability."
    ),
    operation_id="get_scan",
    responses={
        200: {"description": "Full scan detail."},
        404: {"model": ErrorResponse, "description": "Scan not found."},
    },
)
async def get_scan(
    scan_id: uuid.UUID,
    scan_repo: ScanRepository = Depends(get_scan_repository),
) -> ScanFullSchema:
    scan = await scan_repo.get_scan_with_repo(scan_id)
    repo_name = ""
    if hasattr(scan, "repository") and scan.repository is not None:
        repo_name = scan.repository.name or ""
    return scan_to_full(scan, repo_name)


# ---------------------------------------------------------------------------
# GET /api/scans/{scan_id}/patch
# ---------------------------------------------------------------------------


@router.get(
    "/{scan_id}/patch",
    response_model=PatchResponse,
    summary="Get generated patch diff",
    description=(
        "Returns the unified diff produced by the auto-fix pipeline for a completed "
        "scan.  The patch is only present when ``config.allow_auto_fix=true`` was "
        "set on the scan request.  Returns 404 if no patch was generated."
    ),
    operation_id="get_scan_patch",
    responses={
        200: {"description": "Unified diff available."},
        404: {"model": ErrorResponse, "description": "No patch available for this scan."},
    },
)
async def get_scan_patch(
    scan_id: uuid.UUID,
    scan_repo: ScanRepository = Depends(get_scan_repository),
) -> PatchResponse:
    scan = await scan_repo.get_scan(scan_id)
    if not scan.patch_diff:
        raise NotFoundError("Patch", str(scan_id))
    return PatchResponse(scan_id=scan.id, unified_diff=scan.patch_diff)


# ---------------------------------------------------------------------------
# POST /api/scans/{scan_id}/create-pr
# ---------------------------------------------------------------------------


@router.post(
    "/{scan_id}/create-pr",
    response_model=PRResponse,
    summary="Create a GitHub PR from the scan patch",
    description=(
        "Re-applies the stored patch to a fresh workspace, runs validation "
        "and breaking-change checks, then creates a GitHub PR only when all "
        "safety gates pass.  Requires ``GITHUB_TOKEN`` and a GitHub source scan."
    ),
    operation_id="create_scan_pr",
    responses={
        200: {"description": "PR creation result."},
        400: {"model": ErrorResponse, "description": "Cannot create PR for this scan."},
        404: {"model": ErrorResponse, "description": "Scan or patch not found."},
    },
)
async def create_scan_pr(
    scan_id: uuid.UUID,
    scan_repo: ScanRepository = Depends(get_scan_repository),
) -> PRResponse:
    from app.application.breaking_change_detector import BreakingChangeDetector
    from app.application.patch_engine import PatchEngine
    from app.application.safe_pr_service import SafePullRequestService
    from app.application.validation_pipeline import ValidationPipeline
    from app.application.virtual_workspace import VirtualWorkspace
    from app.core.config import settings
    from app.infrastructure.github_clone import GitHubCloner
    import os, shutil

    scan = await scan_repo.get_scan(scan_id)
    if not scan.patch_diff:
        raise NotFoundError("Patch", str(scan_id))
    if scan.source_type != "github":
        raise AppError("PR creation is only supported for GitHub source scans.", status_code=400)

    source_reference = scan.source_reference or ""
    base_branch = scan.branch or "main"
    clone_dir = f"/tmp/scans/pr-{scan_id}"

    cloner = GitHubCloner()
    try:
        cloned_path = await cloner.clone(
            repo_url=source_reference,
            dest_dir=clone_dir,
            branch=base_branch,
            timeout=settings.clone_timeout_seconds,
        )
    except Exception as exc:
        raise AppError(f"Failed to clone repository: {exc}", status_code=400) from exc

    try:
        async with VirtualWorkspace.create(cloned_path) as workspace:
            engine = PatchEngine()
            await engine.apply_patch(scan.patch_diff, workspace)

            v_report = await ValidationPipeline().run(workspace)
            b_report = await BreakingChangeDetector().analyze(cloned_path, workspace)

            outcome = await SafePullRequestService().create_fix_pr(
                repo_url=source_reference,
                base_branch=base_branch,
                scan_id=scan_id,
                workspace=workspace,
                validation_report=v_report,
                breaking_report=b_report,
            )
    finally:
        if os.path.exists(clone_dir):
            shutil.rmtree(clone_dir, ignore_errors=True)

    logger.info("api.create_scan_pr", scan_id=str(scan_id), created=outcome.created)
    return PRResponse(
        created=outcome.created,
        pr_url=outcome.pr_url or None,
        pr_number=outcome.pr_number or None,
        branch_name=outcome.branch_name or None,
        reason=outcome.reason or None,
        warnings=outcome.warnings,
    )


# ---------------------------------------------------------------------------
# GET /api/scans/{scan_id}/patch-annotations
# ---------------------------------------------------------------------------

_AGENT_CATEGORY: dict[str, str] = {
    "qa": "qa",
    "developer": "dev",
    "senior_developer": "dev",
    "architect": "arch",
    "senior_architect": "arch",
    "sre": "sre",
    "senior_sre": "sre",
    "security": "security",
    "security_expert": "security",
}
_VALID_SEVERITIES = {"low", "medium", "high", "critical"}


@router.get(
    "/{scan_id}/patch-annotations",
    response_model=list[AnnotationResponse],
    summary="Get inline diff annotations",
    description=(
        "Returns code-level findings that have a ``file_path`` and ``line_number``, "
        "making them suitable for inline rendering in a diff or patch viewer.  "
        "Optionally filter by ``severity`` or ``category``."
    ),
    operation_id="get_scan_patch_annotations",
    responses={
        200: {"description": "List of inline annotations."},
        404: {"model": ErrorResponse, "description": "Scan not found."},
    },
)
async def get_scan_patch_annotations(
    scan_id: uuid.UUID,
    severity: str | None = Query(default=None, description="Filter: low | medium | high | critical."),
    category: str | None = Query(default=None, description="Filter: qa | dev | arch | sre | security."),
    limit: int = Query(default=200, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
    scan_repo: ScanRepository = Depends(get_scan_repository),
) -> list[AnnotationResponse]:
    scan = await scan_repo.get_scan(scan_id)
    annotations: list[AnnotationResponse] = []

    for agent_result in scan.agent_results or []:
        issues = agent_result.issues if isinstance(agent_result.issues, list) else []
        cat = _AGENT_CATEGORY.get(agent_result.agent_name.lower(), "dev")
        for issue in issues:
            if not isinstance(issue, dict):
                continue
            sev = str(issue.get("severity", "medium")).lower()
            if sev not in _VALID_SEVERITIES:
                sev = "medium"
            file_path = issue.get("file_path") or issue.get("location") or None
            line_raw = issue.get("line_number") or issue.get("line")
            line_number: int | None = None
            try:
                line_number = int(line_raw) if line_raw is not None else None  # type: ignore[arg-type]
            except (TypeError, ValueError):
                pass
            # patch-annotations only includes findings with location info
            if not file_path and not line_number:
                continue
            annotations.append(AnnotationResponse(
                file_path=file_path,
                line_number=line_number,
                severity=sev,
                category=cat,
                message=str(issue.get("description") or issue.get("message") or ""),
            ))

    if severity:
        annotations = [a for a in annotations if a.severity == severity.lower()]
    if category:
        annotations = [a for a in annotations if a.category == category.lower()]

    return annotations[offset : offset + limit]


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _resolve_source_reference(request: ScanRunRequest) -> tuple[str, str]:
    """Return (source_reference, repo_name) for the given request.

    Note: GitHub web tree URLs are already normalised by ``ScanRunRequest._validate_source``
    before this function is called, so ``repository_url`` is always a clean clone URL here.
    """
    if request.source_type == "github":
        url = request.repository_url or ""
        # removesuffix (Python 3.9+) — rstrip(".git") is a character-strip bug
        name = url.rstrip("/").removesuffix(".git").rsplit("/", 1)[-1] or "repository"
        return url, name

    if request.source_type == "local":
        path = request.local_path or ""
        name = Path(path).name or "repository"
        return path, name

    raise ValidationError(f"Unsupported source_type: '{request.source_type}'.")


def _scan_to_summary(scan: ScanModel) -> ScanSummarySchema:
    """Map a ScanModel to the frontend-aligned ScanSummarySchema (delegates to mapper)."""
    repo_name = ""
    if hasattr(scan, "repository") and scan.repository is not None:
        repo_name = scan.repository.name or ""
    return scan_to_summary(scan, repo_name)



