/**
 * Re-exports from the generated API client types.
 * Import from here or directly from '@/generated/api-client'.
 */
export type {
  RiskLevel,
  Severity,
  AgentType,
  ImpactLevel,
  ScanOperationMode,
  ScanStatus,
  ScanMode,
  ScanDepth,
  SourceType,
  LogLevel,
  AgentScore,
  Issue,
  ArchitectureDrift,
  TrendPoint,
  ValidationReport,
  BreakingChangeReport,
  FixPR,
  HunkAnnotation,
  FileAnnotation,
  PatchAnnotations,
  ScanSummary,
  Scan,
  RepositoryListItem,
  Repository,
  LocalUser,
  CreateRepositoryRequest,
  UpdateRepositoryRequest,
  RepositoryListResponse,
  ScanConfig,
  ScanSourceType,
  RunScanRequest,
  RunScanResponse,
  ScanStatusResponse,
  ScanListParams,
  ScanListResponse,
  CreatePRResponse,
  BranchesResponse,
  ScanLogEntry,
  RecentRepo,
  EstimatedTime,
} from '@/generated/api-client';
